### PR TITLE
update changelog for 1.27.101

### PR DESCRIPTION
**Pull request by haitch**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

update changelog for 1.27.101-akslts

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by haitch** [comment]
test fail investigated and pending on: https://github.com/aks-lts/kubernetes/pull/37

**Review by jeremyrickard — APPROVED** [review]

**Review by m-chau — APPROVED** [review]

**Pull request merged**
